#!/bin/bash

# ANSI Colors
YEL='\033[93m'
NC='\033[0m'

S=("     ~  ~  ~     " "    ~  ~  ~  ~    " "     ~  ~  ~     ")
B=(
"  (             )  "
"   (  S S S S  )   "
"    ( S S S S )    "
"   ____________   "
"  \\____________/  ",
"   \\          /   ",
"    \\________/    "
)

# 1. Gradual Build
t=""
for l in "${S[@]}" "${B[@]}"; do
    clear
    t+="$l\n"
    echo -e "${YEL}$t${NC}"
    sleep 0.2
done

# 2. Animation Loop
f=0
while true; do
    clear
    ((f++))
    for i in "${!S[@]}"; do
        [ $(( (f+i)%2 )) -eq 0 ] && echo -ne "  " || echo -ne " "
        echo -e "${YEL}${S[$i]}${NC}"
    done
    for l in "${B[@]}"; do
        if [[ "$l" == *"S"* ]]; then
            [ $((f%2)) -eq 0 ] && char="âˆ«" || char="Â§"
            echo -e "${YEL}${l//S/$char}${NC}"
        else
            echo -e "${YEL}$l${NC}"
        fi
    done
    sleep 0.3
done
